import React from 'react';
import { MatchPrediction } from '../types';
import { useStore } from '../store/useStore';

interface AiCuratedParlayCardProps {
    predictions: MatchPrediction[];
}

const LayersIcon: React.FC<{className?: string}> = ({className}) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
);

export const AiCuratedParlayCard: React.FC<AiCuratedParlayCardProps> = ({ predictions }) => {
    const addAllToTicket = useStore(state => state.addAllToTicket);

    if (!predictions || predictions.length === 0) {
        return null;
    }

    const combinedOdds = predictions.reduce((acc, p) => acc * p.odds, 1);
    const potentialReturn = 10 * combinedOdds; // Based on a $10 stake example

    const handleAdd = () => {
        addAllToTicket(predictions);
    }

    return (
        <section className="bg-gradient-to-br from-sky-500/10 to-brand-bg-light p-6 rounded-lg border border-sky-500/30 shadow-lg">
            <div className="flex items-center gap-3 mb-4">
                <LayersIcon className="w-6 h-6 text-sky-400" />
                <h2 className="text-2xl font-bold text-brand-text-primary">AI Curated Parlay</h2>
            </div>
            <p className="text-sm text-brand-text-secondary mb-4">A high-value parlay generated by combining multiple AI predictions with positive expected value.</p>
            
            <div className="space-y-2 mb-4">
                {predictions.map(p => (
                    <div key={p.id} className="bg-brand-bg-dark p-2 rounded-md flex justify-between items-center text-sm">
                        <div>
                            <p className="font-bold text-brand-text-primary">{p.prediction}</p>
                            <p className="text-xs text-brand-text-secondary truncate max-w-[200px] md:max-w-xs">{p.teamA} vs {p.teamB}</p>
                        </div>
                        <span className="font-bold text-brand-yellow">{p.odds.toFixed(2)}</span>
                    </div>
                ))}
            </div>

            <div className="bg-brand-bg-dark p-4 rounded-lg flex justify-between items-center mb-4">
                <div>
                    <p className="text-sm text-brand-text-secondary">Combined Odds</p>
                    <p className="text-2xl font-bold text-brand-yellow">{combinedOdds.toFixed(2)}</p>
                </div>
                 <div className="text-right">
                    <p className="text-sm text-brand-text-secondary">$10 Stake Returns</p>
                    <p className="text-2xl font-bold text-brand-green">${potentialReturn.toFixed(2)}</p>
                </div>
            </div>

            <button
                onClick={handleAdd}
                className="w-full bg-sky-500 text-white font-bold py-3 rounded-lg hover:bg-sky-600 transition-colors"
            >
                Add Parlay to Ticket
            </button>
        </section>
    );
};
