import React, { useState, useEffect } from 'react';
import { LiveMatchPrediction, UserBet, BankrollState } from '../types';

interface LiveBetModalProps {
  match: LiveMatchPrediction;
  onClose: () => void;
  onPlaceBet: (bet: UserBet) => Promise<boolean>;
  bankroll: BankrollState | null;
}

const XIcon: React.FC<{className?: string}> = ({className}) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
)

export const LiveBetModal: React.FC<LiveBetModalProps> = ({ match, onClose, onPlaceBet, bankroll }) => {
    const [stake, setStake] = useState(10);
    const [isPlacingBet, setIsPlacingBet] = useState(false);
    
    useEffect(() => {
        const handleKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') onClose();
        };
        document.addEventListener('keydown', handleKeyDown);
        return () => document.removeEventListener('keydown', handleKeyDown);
    }, [onClose]);

    const handlePlaceBet = async () => {
        if (!bankroll || stake <= 0 || stake > bankroll.current) {
            alert("Invalid stake amount.");
            return;
        }
        setIsPlacingBet(true);
        const success = await onPlaceBet({
            id: '', // Will be generated by service
            match: match,
            stake: stake,
            odds: match.liveOdds,
            status: 'pending',
            payout: null,
            placedAt: new Date(),
        });
        if (success) {
            onClose();
        }
        setIsPlacingBet(false);
    };
    
    const potentialReturn = stake * match.liveOdds;

    return (
        <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4 animate-fade-in" onClick={onClose}>
            <div className="bg-brand-bg-light rounded-xl shadow-2xl w-full max-w-md animate-modal-enter" onClick={e => e.stopPropagation()}>
                <header className="p-6 border-b border-brand-border flex justify-between items-center">
                    <div>
                        <p className="text-sm text-brand-text-secondary">Live Bet</p>
                        <h2 className="text-2xl font-bold text-brand-text-primary">{match.teamA} vs {match.teamB}</h2>
                    </div>
                    <button onClick={onClose} className="p-2 rounded-full text-brand-text-secondary hover:bg-brand-border"><XIcon className="w-6 h-6"/></button>
                </header>
                <main className="p-6">
                    <div className="bg-brand-bg-dark p-4 rounded-lg text-center">
                        <p className="font-bold text-lg text-brand-text-primary">{match.prediction}</p>
                        <p className="text-5xl font-bold text-brand-yellow my-2">{match.liveOdds.toFixed(2)}</p>
                        <p className="text-sm text-brand-text-secondary">Current Live Odds</p>
                    </div>

                    <div className="mt-6">
                        <label htmlFor="stake" className="block text-sm font-medium text-brand-text-secondary mb-1">Stake</label>
                        <div className="relative">
                            <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-brand-text-secondary">$</span>
                            <input 
                                type="number" 
                                id="stake"
                                value={stake}
                                onChange={(e) => setStake(Number(e.target.value))}
                                className="w-full bg-brand-bg-dark border border-brand-border rounded-md pl-7 pr-4 py-2 text-brand-text-primary focus:ring-2 focus:ring-brand-green focus:border-brand-green"
                            />
                        </div>
                    </div>
                    
                    <div className="mt-4 p-4 rounded-lg bg-brand-bg-dark flex justify-between items-center">
                        <span className="text-sm font-bold text-brand-text-secondary">Potential Return</span>
                        <span className="text-xl font-bold text-brand-green">{potentialReturn.toLocaleString('en-US', {style: 'currency', currency: 'USD'})}</span>
                    </div>

                </main>
                <footer className="p-6 bg-brand-bg-dark/50 rounded-b-xl">
                     <button 
                        onClick={handlePlaceBet}
                        disabled={isPlacingBet || stake <= 0 || (bankroll && stake > bankroll.current)}
                        className="w-full bg-brand-red text-white font-bold py-3 rounded-lg hover:bg-opacity-80 transition-colors disabled:bg-gray-500 disabled:cursor-not-allowed"
                    >
                        {isPlacingBet ? 'Placing Bet...' : `Place ${stake.toLocaleString('en-US', {style: 'currency', currency: 'USD'})} Live Bet`}
                    </button>
                </footer>
            </div>
        </div>
    );
};