import React, { useMemo, useState } from 'react';
import { TicketSelection, UserBet, BankrollState, UserSettings } from '../types';
import * as api from '../services/apiService';
import { TicketVariationCard } from './TicketVariationCard';

interface TicketBuilderProps {
    selections: TicketSelection[];
    onRemove: (prediction: TicketSelection) => void;
    onPlaceBet: (bet: UserBet) => Promise<boolean>;
    bankroll: BankrollState | null;
    userSettings: UserSettings | null;
}

const TrashIcon: React.FC<{className?: string}> = ({className}) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
);

export const TicketBuilder: React.FC<TicketBuilderProps> = ({ selections, onRemove, onPlaceBet, bankroll, userSettings }) => {
    const [stake, setStake] = useState(10);
    const [isPlacingBet, setIsPlacingBet] = useState(false);
    
    const { totalOdds, potentialReturn } = useMemo(() => {
        const odds = selections.reduce((acc, p) => acc * p.odds, 1);
        return {
            totalOdds: odds,
            potentialReturn: stake * odds
        };
    }, [selections, stake]);

    const stakeError = useMemo(() => {
        if (stake <= 0) return "Stake must be positive.";
        if (bankroll && stake > bankroll.current) return "Stake exceeds current bankroll.";
        if (userSettings && stake > userSettings.maxStakePerBet) return `Stake exceeds your max bet limit of $${userSettings.maxStakePerBet}.`;
        return null;
    }, [stake, bankroll, userSettings]);

    const handlePlaceBet = async () => {
        if (stakeError) {
            alert(stakeError);
            return;
        }
        setIsPlacingBet(true);
        const success = await onPlaceBet({
            id: '', // Will be generated by service
            match: selections[0], // Main match for reference
            selections: selections,
            stake: stake,
            odds: totalOdds,
            status: 'pending',
            payout: null,
            placedAt: new Date(),
        });

        if (success) {
            setStake(10);
        }
        setIsPlacingBet(false);
    };

    return (
        <section className="bg-brand-bg-light p-6 rounded-lg border border-brand-border shadow-lg">
            <h2 className="text-xl font-bold text-brand-text-primary mb-4">Bet Ticket</h2>
            
            <div className="space-y-3 max-h-60 overflow-y-auto pr-2">
                {selections.map(selection => (
                    <div key={selection.id} className="bg-brand-bg-dark p-3 rounded-md flex justify-between items-center">
                        <div>
                            <p className="text-sm font-bold text-brand-text-primary">{selection.prediction}</p>
                            <p className="text-xs text-brand-text-secondary">{selection.teamA} vs {selection.teamB}</p>
                        </div>
                        <div className="flex items-center gap-4">
                           <span className="font-bold text-brand-yellow">{selection.odds.toFixed(2)}</span>
                           <button onClick={() => onRemove(selection)} className="text-brand-text-secondary hover:text-brand-red"><TrashIcon className="w-4 h-4"/></button>
                        </div>
                    </div>
                ))}
            </div>

            <div className="mt-4 border-t border-brand-border pt-4">
                <div className="flex justify-between items-center text-sm font-bold">
                    <p className="text-brand-text-secondary">{selections.length} Picks (Parlay)</p>
                    <p className="text-brand-text-primary">Total Odds: <span className="text-brand-yellow">{totalOdds.toFixed(2)}</span></p>
                </div>
            </div>

            <div className="mt-4">
                <label htmlFor="stake" className="block text-sm font-medium text-brand-text-secondary mb-1">Stake</label>
                <div className="relative">
                    <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-brand-text-secondary">$</span>
                    <input 
                        type="number" 
                        id="stake"
                        value={stake}
                        onChange={(e) => setStake(Number(e.target.value))}
                        className={`w-full bg-brand-bg-dark border rounded-md pl-7 pr-4 py-2 text-brand-text-primary focus:ring-2 focus:ring-brand-green focus:border-brand-green ${stakeError ? 'border-brand-red' : 'border-brand-border'}`}
                    />
                </div>
                {stakeError && <p className="text-xs text-brand-red mt-1">{stakeError}</p>}
            </div>

            <div className="mt-4 p-4 rounded-lg bg-brand-bg-dark flex justify-between items-center">
                <span className="text-sm font-bold text-brand-text-secondary">Potential Return</span>
                <span className="text-xl font-bold text-brand-green">{potentialReturn.toLocaleString('en-US', {style: 'currency', currency: 'USD'})}</span>
            </div>

            <button 
                onClick={handlePlaceBet}
                disabled={isPlacingBet || !!stakeError || selections.length === 0}
                className="w-full mt-6 bg-brand-green text-white font-bold py-3 rounded-lg hover:bg-opacity-90 transition-colors disabled:bg-gray-500 disabled:cursor-not-allowed"
            >
                {isPlacingBet ? 'Placing Bet...' : `Place ${stake.toLocaleString('en-US', {style: 'currency', currency: 'USD'})} Bet`}
            </button>
        </section>
    );
};